const siteStructure = [
    {
        id:1,
        name:'发现音乐',
        isOuterLink:false,
        routerName:'index',
        isHot:false,
        children:[
            {
                id:10,
                name:'推荐',
                routerName:'discoverRecommend'
            },
            {
                id:11,
                name:'排行榜',
                routerName:'discoverToplist'
            },
            {
                id:12,
                name:'歌单',
                routerName:'discoverPlaylist'
            },
            {
                id:13,
                name:'主播电台',
                routerName:'discoverDjRadioIndex'
            },
            {
                id:14,
                name:'歌手',
                routerName:'discoverSingerIndex'
            },
            {
                id:15,
                name:'新碟上架',
                routerName:'discoverNewAlbum'
            }
        ]
    },
    {
        id:2,
        name:'我的音乐',
        isOuterLink:false,
        routerName:'my',
        router:'/my',
        isHot:false
    },
    {
        id:3,
        name:'朋友',
        isOuterLink:false,
        routerName:'friend',
        router:'/friend',
        isHot:false
    },
    {
        id:4,
        name:'商城',
        isOuterLink:true,
        href:'https://music.163.com/store/product',
        isHot:false
    },
    {
        id:5,
        name:'音乐人',
        isOuterLink:true,
        href:'https://music.163.com/nmusician/web/recruit',
        isHot:false
    },
    {
        id:6,
        name:'下载客户端',
        isOuterLink:false,
        routerName:'download',
        isHot:true
    }
]

export default siteStructure